language: node_js
node_js:
  - node
  - v5
  - v4
  - '0.12'
  - '0.10'
branches:
only:
  - master
  - development
script: npm test
notifications:
  slack: vulgardisplayofpower:wJ5sUavcVl4FNg98KI3OHg2G
